### ISSUE TITLE
Partition to codon position

### ISSUE THREAD

**Issue by mariespe** [marekborowiec/AMAS#14]
Currently it doesn't seem to be possible to output partition files with codon positions when concatenating loci. Would it perhaps be possible to add an option for this, e.g generating a partition file like this?

DNA, p1=1-60\3,2-60\3
DNA, p2=3-60\3

or

DNA, p1=1-60\3
DNA, p2=2-60\3
DNA, p3=3-60\3

It would also be great to be able to split based on such partition files.

**Comment by marekborowiec** [comment]
It is now possible to write a partitions file with each codon position in a separate partitions with "-n" flag to "concat" command. It was already possible to split matrices using partitioning scheme in your second example. See Readme. Note that for AMAS you need to provide a file without anything preceding partition name, like "DNA, ", although you can format the partitions file like that using the "-y raxml" option when concatenating.
