### ISSUE TITLE
Cannot Generate by Taxon Summary Statistics

### ISSUE THREAD

**Issue by kevinliam** [marekborowiec/AMAS#4]
Hello,

I'm unable to generate summary statistics using the summary command for a fasta file of dna sequences. I've attached the fasta file and the output file "summary.txt".

Here's the command I used:

```
amas summary -i Noctuidae_Amphipyrinae_Manuscript_1_v001.fasta -f fasta -
d dna --by-taxon
```

Best,
Kevin
[fasta_summary.zip](https://github.com/marekborowiec/AMAS/files/1666078/fasta_summary.zip)

**Comment by marekborowiec** [comment]
Dear Kevin,

I cannot replicate your issue. It works for me using your files and command.

**Comment by kevinliam** [comment]
Huh! Weird. You had two files produced by the command?

Thanks for looking into my problem!

**Comment by marekborowiec** [comment]
I did, as expected. Have you tried cloning the latest version?
